CELL = {
  INVALIDSQUARE : -1,
  EMPTYSQUARE : 0,
  WHITEPIECE : 1,
  BLACKPIECE : 2,
};

/**
 * DraughtMap
 * @param gl {WebGLRenderingContext}
 * @constructor
 */
function DraughtMap(){
  //construtor
  this.map =[
    [CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE],
    [CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE],
    [CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE],
    [CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE],
    [CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE],
    [CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE],
    [CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE],
    [CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE],
  ];

  this.sizeN = this.map.length;
};

DraughtMap.prototype.resetMap = function (){
  this.map =[
    [CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE],
    [CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE],
    [CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE, CELL.WHITEPIECE, CELL.INVALIDSQUARE],
    [CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE],
    [CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE, CELL.EMPTYSQUARE, CELL.INVALIDSQUARE],
    [CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE],
    [CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE],
    [CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE, CELL.INVALIDSQUARE, CELL.BLACKPIECE],
  ];
}

DraughtMap.prototype.getsizeN = function(){
  return this.sizeN;
}

DraughtMap.prototype.getPos = function (y, x){
  return this.map[y][x];
}
